version: "2"

services: 
  api:
    build: .
    command: npm run dev
    environment:
      - DEBUG=server:*,server-redis:*,worker:*,converter-ffmpeg:*,converter-redis:*,examineFile:*
      - DEBUG_COLORS=true
      - WORKER_STARTUP_SECONDS=15
    links:
      - redis
      - rabbitmq
    depends_on:
      - redis
      - rabbitmq
    volumes: 
      - api-deps:/code/node_modules
      - .:/code

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:latest
    # environment:
    #  - RABBITMQ_HIPE_COMPILE=1

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    image: av-converter-nginx
    ports: 
      - 8080:80
    links:
      - api
    depends_on:
      - api  
    volumes:
      - ./backend/downloads/:/code/backend/downloads
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/code/frontend

volumes:
  api-deps: